# frozen_string_literal: true

require 'rails_helper'

RSpec.describe MoneyTransaction do
  describe 'reference' do
    subject(:money_transaction_reference) { money_transaction.reference }

    let(:money_transaction) { described_class.create(description: 'fee') }

    it 'is automatically generated by the database' do
      expect(money_transaction_reference).not_to be_blank
    end
  end
end
